name: Semgrep Security Check

on: [push, pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep
      run: semgrep --config p/owasp-top-ten
